project_id = "rwouwxqggjjacbpbhqsn"

[functions.sprout-profiles]
verify_jwt = false

[functions.update-report]
verify_jwt = false

[functions.research-brand-identity]
verify_jwt = false

[functions.generate-post-image]
verify_jwt = false

[functions.trigger-scheduled-reports]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.firecrawl-map]
verify_jwt = false

[functions.firecrawl-crawl]
verify_jwt = false