/** Rows shaped like the production tables, for the serializer and route tests. */
export const CLIENT = {
  id: "c-bader", name: "Bader Law", website_url: "https://baderlaw.com", company_slug: "bader-law", primary_platforms: ["Instagram", "TikTok", "Facebook", "LinkedIn", "YouTube"], geo: "US", language: "en", timezone: "America/New_York",
  content_pillars: [{ name: "Know your rights", description: "Plain explanations of legal situations." }], social_keywords: ["personal injury", "car accident lawyer"], trends_keywords: null as string | null,
  brand_identity: { primary_color: "#1F3A5F", secondary_color: "#FFFFFF", accent_color: "#C8A951", font_family: "Montserrat", visual_style: "clean, confident", tone_of_voice: "direct and reassuring", logo_description: "Serif wordmark", design_elements: "gold rules", background_style: "navy" },
  brand_notes: "[VOICE:plain]\nShort sentences.", brief_text: "Bader Law represents injury victims.", logo_url: "https://x.supabase.co/storage/v1/object/public/brand-assets/logos/bader.png",
  design_style_synthesis: { synthesized_at: "2026-09-20T10:00:00.000Z", source_count: 8, reference_pipeline_version: 1 }, harvested_design_references: [{ path: "c-bader/social-1.jpg" }, { path: "c-bader/social-2.jpg" }, { path: "c-bader/social-3.jpg" }], design_references: null as unknown,
  sprout_customer_id: null as string | null, hub_company_name: null as string | null, media_backend: "higgsfield", archived_at: null as string | null, created_at: "2026-05-01T10:00:00.000Z", updated_at: "2026-09-30T10:00:00.000Z", created_by: "u1", demo_job_id: null as string | null,
};
export const SPROUT_PROFILE = { id: "sp-1", client_id: "c-bader", sprout_profile_id: 123456, profile_name: "Bader Law", native_name: "baderlaw", network_type: "instagram", native_link: "https://instagram.com/baderlaw", is_active: true };
export const COMPETITOR_SET = { id: "set-1", client_id: "c-bader", status: "confirmed", notes: "Reviewed.", source: "ai", rivaliq_landscape_id: "L123", confirmed_by: "u1", confirmed_at: "2026-09-10T10:00:00.000Z", created_at: "2026-09-09T10:00:00.000Z", updated_at: "2026-09-10T10:00:00.000Z", demo_job_id: null as string | null };
export const COMPETITOR = { id: "comp-1", set_id: "set-1", client_id: "c-bader", name: "Morgan & Morgan", website_url: "https://www.forthepeople.com", rationale: "National injury firm.", similarity_score: 0.91, source: "ai", is_selected: true, selected_rank: 1, rivaliq_company_id: "RC1", profile_detection: { status: "found" }, created_at: "2026-09-09T10:00:00.000Z" };
export const HANDLE = { id: "h-1", competitor_id: "comp-1", client_id: "c-bader", platform: "instagram", handle: "forthepeople", profile_url: "https://instagram.com/forthepeople", is_active: true, followers: 250000, detection_confidence: 0.95, source: "auto", detected_at: "2026-09-09T10:00:00.000Z" };
export const REPORT_DATA = {
  status: "success", client_name: "Bader Law", report_date: "2026-09-01", started_at: "2026-09-01T07:00:00.000Z", completed_at: "2026-09-01T07:38:00.000Z", duration_minutes: 38, trend_status: "ok", gamma_url: "https://gamma.app/docs/bader-aug", gamma_status: "ok",
  report_period: { current_month: { start: "2026-08-01", end: "2026-08-31" }, previous_month: { start: "2026-07-01", end: "2026-07-31" } },
  data_counts: { total_recommendations: 12, content_calendar_days: 7, tiktok_trends: 15, instagram_trends: 15, sprout_top_posts: 10, sprout_profiles: 5 },
  metrics_summary: { impressions_change: -20.1, reactions_change: -8.7 }, warnings: ["TikTok trends thin"],
  ai_analysis: { sprout_performance_analysis: { month_over_month_summary: "Reach fell.", key_insights: ["Reels outperformed."], platform_breakdown: [], pillar_alignment: {} }, tiktok_trends_analysis: { overview: "o" }, instagram_trends_analysis: { overview: "i" }, content_recommendations: [{ platform: "Instagram" }], competitive_takeaways: ["Post more Reels."] },
  content_calendar: [{ day: "Monday", date_label: "Sep 8", posts: [{ platform: "Instagram", copy: "Know your rights after a crash.", format: "Reel/Video", pillar: "Know your rights", hashtags: ["#law"], language: "en", posting_time: "18:00", rationale: "r", visual_direction: "Lawyer at desk", ai_visual_prompt: "p" }] }],
  sprout_performance: { overall_totals: { impressions: 120000 }, top_posts: [{ post_id: "sp-post-1", network: "instagram", text: "t", impressions: 5000 }], platform_breakdown: [{ network: "instagram", current: { impressions: 1 } }], month_comparison: { changes: { impressions: { current: 120000, previous: 150000, percent: -20.1 } } } },
  tiktok_trends: { posts: [{ id: 1 }], patterns: { top_hashtags: ["#law"] } }, instagram_trends: { posts: [], patterns: {} }, report_sections: [{ title: "x" }], context: { timezone: "America/New_York" },
};
export const REPORT = { id: "rep-1", client_id: "c-bader", report_type: "weekly", status: "completed", date_range_start: "2026-08-01", date_range_end: "2026-08-31", gamma_url: "https://gamma.app/docs/bader-aug", duration_minutes: 38, report_data: REPORT_DATA, created_at: "2026-09-01T07:00:00.000Z", created_by: "u1", demo_job_id: null as string | null };
export const COMPETITIVE_DATA = {
  source: "rivaliq", provider_status: "ok", landscape: { id: "L123", name: "Bader Law", matched_by: "slug", focus_company_id: "RC0", companies: 4 }, period: { start: "2026-08-25", end: "2026-09-24", days: 31 },
  totals: { posts_analyzed: 412, post_windows: 3, rivaliq_calls: 14 },
  aggregates: { client_name: "Bader Law", metrics_available: true, companies: [{ company_id: "RC1", name: "Morgan & Morgan", is_client: false, in_confirmed_top: true, post_count: 120, cadence_per_week: 27, engagement_rate_avg: 0.012, channel_mix: { instagram: 60 }, top_hashtags: ["#law"], top_posts: [{ url: "https://instagram.com/p/1", engagement: 900 }] }] },
  ai_analysis: { executive_summary: "Competitors post daily.", benchmark_scorecard: { client_score: 42, dimensions: [{ dimension: "cadence", client: 3, competitor_avg: 20 }] }, gaps_for_client: [{ gap: "Cadence", platform: "instagram", why_it_matters: "w", suggested_play: "s" }], winner_teardown: [], competitor_breakdowns: [], posting_time_insights: {}, recommended_schedule: {} },
  generated_at: "2026-09-25T08:00:00.000Z", schema_note: "v1",
};
export const COMPETITIVE_REPORT = { id: "crep-1", client_id: "c-bader", set_id: "set-1", report_data: COMPETITIVE_DATA, status: "complete", gamma_url: "https://gamma.app/docs/bader-comp", duration_minutes: 22, date_range_start: "2026-08-25", date_range_end: "2026-09-24", created_by: "u1", created_at: "2026-09-25T07:30:00.000Z", demo_job_id: null as string | null };
export const POST = { id: "post-1", client_id: "c-bader", report_id: "rep-1", recommendation_index: null as number | null, version: 1, platform: "Instagram", post_copy: "Know your rights after a crash.", hashtags: ["#law"], cta: "Call us", concept: "Rights explainer", visual_direction: "Lawyer at desk", format: "Reel/Video", source: "calendar", created_at: "2026-09-02T10:00:00.000Z", created_by: "u1", media_urls: ["https://x.supabase.co/storage/v1/object/public/generated-media/c-bader/1.png"], video_edits: null as unknown, variant_group_id: "vg-1", is_selected: true, variant_angle: "Reference creative plan-1: desk", is_approved: true, approved_at: "2026-09-03T10:00:00.000Z", approved_by: "u1", rejected_at: null as string | null, rejection_reason: null as string | null, rejection_note: null as string | null, archived_at: null as string | null, calendar_post_key: null as string | null, finishing: "done", demo_job_id: null as string | null };
export const MEDIA_JOB = { id: "mj-1", client_id: "c-bader", post_iteration_id: "post-1", kind: "image", provider: "higgsfield", request_id: "req-secret", model_path: "/models/x", status: "completed", input: { creative_plan_id: "plan-1", creative_frame_index: 0 }, output_url: "https://x.supabase.co/storage/v1/object/public/generated-media/c-bader/1.png", seed_image_url: null as string | null, error: null as string | null, created_by: "u1", created_at: "2026-09-02T09:50:00.000Z", updated_at: "2026-09-02T09:55:00.000Z", review: { dirty: false, reason: "clean", has_logo: true }, reviewed_at: "2026-09-02T09:55:00.000Z", demo_job_id: null as string | null };
export const SCHEDULE = { id: "rs-1", client_id: "c-bader", frequency: "monthly", is_active: true, next_run_at: "2026-10-07T07:15:00.000Z", last_run_at: "2026-09-07T07:15:00.000Z", trends_date_range_days: null as number | null, analysis_date_range_days: null as number | null, created_by: "u1", created_at: "2026-06-01T10:00:00.000Z", updated_at: "2026-09-07T07:15:00.000Z", report_kind: "social", run_day_of_month: 7, range_mode: "previous_month", last_result: "triggered", pending_competitive_report_id: null as string | null, dispatch_claimed_at: null as string | null };
export const SCHEDULED_POST = { id: "sch-post-1", client_id: "c-bader", report_id: "rep-1", sprout_post_id: "9988", profile_id: "sp-1", platform: "instagram", scheduled_time: "2026-09-10T15:00:00.000Z", status: "scheduled", post_content: "Know your rights.", media_url: "https://x/1.png", created_at: "2026-09-03T10:00:00.000Z", created_by: "u1" };
export const ALERT = { id: "al-1", client_id: "c-bader", window_start: "2026-09-15", window_end: "2026-09-21", topic: "Back to school safety", topic_key: "back-to-school-safety", summary: "Three competitors posted about it.", companies: ["Morgan & Morgan", "Cellino"], platforms: ["instagram"], post_urls: ["https://instagram.com/p/2"], post_count: 4, confidence: 0.8, status: "new", created_at: "2026-09-22T06:00:00.000Z" };
export const DESIGN_SYSTEM = { id: "ds-1", client_id: "c-bader", version: 2, status: "approved", system: { version: 1, tokens: { font: { family: "Montserrat" }, colors: { ink: "#1F3A5F", surface: "#FFFFFF", accent: "#C8A951", background: "#0B1E33" } }, templates: [{ id: "t-quote", name: "Quote card", formats: ["square", "portrait"] }], logo_aspect: 3.2 }, previews: [{ template_id: "t-quote", format: "square", path: "previews/c-bader/v2-t-quote.png", url: "https://x/previews/v2-t-quote.png" }], built_from: ["c-bader/social-1.jpg"], approved_by: "u1", approved_at: "2026-09-21T10:00:00.000Z", created_by: "u1", created_at: "2026-09-21T09:00:00.000Z", updated_at: "2026-09-21T10:00:00.000Z" };
